spring:
  r2dbc:
    url: ${POSTGRES_URL_R2DBC:r2dbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  security:
    oauth2:
      client:
        registration:
          portaria-server-oidc:
            provider: spring
            client-id: portaria-server
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI:http://localhost:8080}/login/oauth2/code/{registrationId}
            scope: openid, profile
            client-name: portaria-server-oidc
        provider:
          spring:
            issuer-uri: ${OAUTH_SERVER_URI:http://localhost:9000}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO